version: "3.9"

services:
  db:
    image: postgres:14.5-alpine
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bookings
      POSTGRES_USER: bookings
      POSTGRES_PASSWORD: bookings
    ports:
      - "19999:5432"

  mailhog:
    image: mailhog/mailhog
    logging:
      driver: "none" # disable saving logs
    ports:
      - 19998:1025 # smtp server
      - 19997:8025 # web ui

volumes:
  db_data:
